import './globals.css'
import type {Metadata} from 'next'
import {Assistant} from 'next/font/google'
import {MainLayoutType} from "@/types/Layout";
import IndexHeader from "@/components/Layout/Header/IndexHeader";
import IndexFooter from "@/components/Layout/IndexFooter";
import {ThemeProviderContext} from "@/components/ThemeContext";

const assistant = Assistant({subsets: ['latin']})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({children}: MainLayoutType) => {

    return (
        <html lang="en" dir='rtl'>
        <body className={assistant.className} suppressHydrationWarning={true}>
        <ThemeProviderContext>
            <IndexHeader/>
                {children}
            <IndexFooter/>
        </ThemeProviderContext>
        </body>
        </html>
    )
}

export default RootLayout