export { default as AddFileIcon } from '@/components/Icons/Add File Icon'
export { default as AddUserIcon } from '@/components/Icons/Add User Icon'
export { default as PhoneIcon } from '@/components/Icons/Phone Icon'
export { default as EmailIcon } from '@/components/Icons/Email Icon'
export { default as AcademicIcon } from '@/components/Icons/Academic Icon'
export { default as AccountIcon } from '@/components/Icons/Account Icon'
export { default as CheckIcon } from '@/components/Icons/Check Icon'
export { default as ChevronIcon } from '@/components/Icons/Chevron'
export { default as CloseIcon } from '@/components/Icons/Close Icon'
export { default as DeleteIcon } from '@/components/Icons/Delete Icon'
export { default as EditIcon } from '@/components/Icons/Edit Icon'
export { default as ErrorIcon } from '@/components/Icons/Error Icon'
export { default as FacebookIcon } from '@/components/Icons/Facebook Icon'
export { default as HamburgerIcon } from '@/components/Icons/Hamburger Icon'
export { default as InboxIcon } from '@/components/Icons/Inbox Icon'
export { default as InstagramIcon } from '@/components/Icons/Instagram Icon'
export { default as LockIcon } from '@/components/Icons/Lock Icon'
export { default as MoonIcon } from '@/components/Icons/Moon Icon'
export { default as SunIcon } from '@/components/Icons/Sun Icon'
export { default as UsersIcon } from '@/components/Icons/Users Icon'
export { default as WhatsappIcon } from '@/components/Icons/Whatsapp Icon'
export { default as YoutubeIcon } from '@/components/Icons/Youtube Icon'
export { default as DownloadIcon } from '@/components/Icons/Download Icon'
export { default as ContentIcon } from '@/components/Icons/Content Icon'
export { default as ClockIcon } from '@/components/Icons/Clock Icon'
export { default as MagicIcon } from '@/components/Icons/Magic Icon'
export { default as HelpIcon } from '@/components/Icons/Help Icon'
export { default as MedalIcon } from '@/components/Icons/Medal Icon'
export { default as SettingIcon } from '@/components/Icons/Setting Icon'
export { default as VideoIcon } from '@/components/Icons/Video Icon'
export { default as CopyrightIcon } from '@/components/Icons/Copyright Icon'
